<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>前端监控SDK</title>
    <script src="https://cdn.bootcdn.net/ajax/libs/lodash.js/4.17.21/lodash.core.js"></script>
</head>

<body>
    <div id="container" style="background-color: bisque; height: 100px;">
    </div>
    <div id="container2" style="background-color: red;"></div>

    <script>
        setTimeout(() => {
            document.getElementById('container').innerHTML = `
        <input id="js-error" type="button" value="点击抛出错误" onclick="errorClick()">
        <input id="promise-error1" type="button" value="promise Error1" onclick="promiseError1()">
        <input id="promise-error2" type="button" value="promise Error2" onclick="promiseError2()">
        <input id="ajax-error" type="button" value="ajax-error" onclick="ajaxError()">
        <input id="ajax-success" type="button" value="ajax-success" onclick="ajaxSuccess()">        
        `
        }, 1000);

        setTimeout(() => {
            const divEle = document.createElement('div')
            divEle.innerHTML = `<div elementtiming="meaningful" >有意义的元素</div>`
            document.getElementById('container').appendChild(divEle)
        }, 2000);
        setTimeout(() => {
            const divEle = document.createElement('div')
            divEle.innerHTML = `<div elementtiming="meaningfuxxxxl" >有意义的元素</div>`
            document.getElementById('container').appendChild(divEle);
            // 第二次的不会再观测到了
        }, 3000);
        setTimeout(() => {
            const pEle = document.createElement('p')
            pEle.innerText = Array(10000).join('一')
            document.getElementById('container2').appendChild(pEle)
        }, 3000);

        function errorClick() {
            window.test.xxx = 'xxxxx'
        }

        function promiseError1() {
            return new Promise((resolve, reject) => {
                reject('error1')
            })
        }

        function promiseError1() {
            return new Promise((resolve, reject) => {
                // reject('error1')
                window.test.xxx = 'xxxxx'
            })
        }

        function ajaxError() {
            const xhr = new XMLHttpRequest;
            xhr.open('GET', '/error', true)
            xhr.responseType = 'json'
            xhr.onload = (e) => {
                console.log('onload', e)
            }
            xhr.send()
        }

        function ajaxSuccess() {
            const xhr = new XMLHttpRequest;
            xhr.open('GET', '/success', true)
            xhr.responseType = 'json'
            xhr.onload = (e) => {
                console.log('onload', e)
            }
            xhr.send()
        }

        const handleError = (e) => {

        }
    </script>
    <!-- 资源错误加载 -->
    <script src="404.js"></script>
</body>

</html>